ROOT			= ../../../..

NAME		= JAR2XML
PACKAGE		= org.osgi.tools.jar2xml
VERSION		= 1.0.0
IMPORTS		= $(ROOT)/jar/bcel.jar

SOURCES		= \
	 JAR2XML.java
	

BTOOL = \
	-analyse \
	-property name $(NAME) \
	-property version $(VERSION)

include $(ROOT)/cnf/package.mk




