/*
 * Copyright (c) The OSGi Alliance (2004). All Rights Reserved.
 * 
 * Implementation of certain elements of the OSGi Specification may be subject
 * to third party intellectual property rights, including without limitation,
 * patent rights (such a third party may or may not be a member of the OSGi
 * Alliance). The OSGi Alliance is not responsible and shall not be held
 * responsible in any manner for identifying or failing to identify any or all
 * such third party intellectual property rights.
 * 
 * This document and the information contained herein are provided on an "AS IS"
 * basis and THE OSGI ALLIANCE DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO ANY WARRANTY THAT THE USE OF THE INFORMATION
 * HEREIN WILL NOT INFRINGE ANY RIGHTS AND ANY IMPLIED WARRANTIES OF
 * MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT WILL THE
 * OSGI ALLIANCE BE LIABLE FOR ANY LOSS OF PROFITS, LOSS OF BUSINESS, LOSS OF
 * USE OF DATA, INTERRUPTION OF BUSINESS, OR FOR DIRECT, INDIRECT, SPECIAL OR
 * EXEMPLARY, INCIDENTIAL, PUNITIVE OR CONSEQUENTIAL DAMAGES OF ANY KIND IN
 * CONNECTION WITH THIS DOCUMENT OR THE INFORMATION CONTAINED HEREIN, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH LOSS OR DAMAGE.
 * 
 * All Company, brand and product names may be trademarks that are the sole
 * property of their respective owners. All rights reserved.
 * 
 */

/*
 * REVISION HISTORY:
 *
 * Date         Author(s)
 * CR           Headline
 * ===========  ==============================================================
 * 03/05/2005   Alexandre Santos
 * 38           Implement MEGTCK for the application RFC 
 * ===========  ==============================================================
 */
package org.osgi.test.cases.application.tb2.MegletHandle;

import org.osgi.service.application.ApplicationDescriptor;
import org.osgi.service.application.meglet.MegletDescriptor;
import org.osgi.service.application.meglet.MegletHandle;
import org.osgi.test.cases.application.tbc.ApplicationTestControl;
import org.osgi.test.cases.application.tbc.TestInterface;
import org.osgi.test.cases.application.tbc.util.MessagesConstants;

/**
 * @methodUnderTest org.osgi.service.application.MegletHandle#GetApplicationDescriptor
 * @generalDescription This Test Class Validates the implementation of
 *                     <code>GetApplicationDescriptor<code> method, according to MEG reference
 *                     documentation.
 */
public class GetApplicationDescriptor implements TestInterface {
	private ApplicationTestControl tbc;

	public GetApplicationDescriptor(ApplicationTestControl tbc) {
		this.tbc = tbc;
	}

	public void run() {
		testGetApplicationDescriptor001();
		testGetApplicationDescriptor002();
	}

	/**
	 * @testID testGetApplicationDescriptor001
	 * @testDescription Asserts if the returned descriptor is an
	 * 					instance of MegletDescriptor.
	 */
	public void testGetApplicationDescriptor001() {
		tbc.log("#testGetApplicationDescriptor001");
		MegletHandle handle = tbc.getAppHandle();
		ApplicationDescriptor descriptor = handle.getApplicationDescriptor();
		tbc.assertTrue(MessagesConstants.getMessage(MessagesConstants.ASSERT_TRUE, new String[] { "the returned descriptor is an" +
				" instance of MegletDescriptor" }), (descriptor instanceof MegletDescriptor));
	}
	
	/**
	 * @testID testGetApplicationDescriptor002
	 * @testDescription Asserts if the returned descriptor is equal to the descriptor generated
	 * 					by our meglet installation.
	 */
	public void testGetApplicationDescriptor002() {
		tbc.log("#testGetApplicationDescriptor002");
		MegletHandle handle = tbc.getAppHandle();
		ApplicationDescriptor descriptor = handle.getApplicationDescriptor();
		tbc.assertEquals("Asserting if the returned descriptor is equal to descriptor generated by our meglet installation.", 
				tbc.getAppDescriptor1(), descriptor);
	}	
}
