/*******************************************************************************
 * Copyright (c) Contributors to the Eclipse Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 *******************************************************************************/

package org.osgi.test.cases.feature.assertj;

import org.assertj.core.api.AbstractObjectAssert;
import org.osgi.service.feature.FeatureArtifact;

/**
 * Abstract base class for {@link FeatureArtifact} specific assertions -
 * Generated by CustomAssertionGenerator.
 */
public abstract class AbstractFeatureArtifactAssert<S extends AbstractFeatureArtifactAssert<S, A>, A extends FeatureArtifact>
	extends AbstractObjectAssert<S, A> {

	/**
	 * Creates a new <code>{@link AbstractFeatureArtifactAssert}</code> to make
	 * assertions on actual FeatureArtifact.
	 *
	 * @param actual the FeatureArtifact we want to make assertions on.
	 */
	protected AbstractFeatureArtifactAssert(A actual, Class<S> selfType) {
		super(actual, selfType);
	}

	public FeatureIDAssert hasIDThat() {
		isNotNull();
		return FeatureIDAssert.assertThat(actual.getID())
			.as(actual + ".id");
	}

}
