/*******************************************************************************
 * Copyright (c) Contributors to the Eclipse Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 *******************************************************************************/

package org.osgi.test.cases.feature.assertj;

import org.osgi.service.feature.Feature;

/**
 * {@link Feature} specific assertions - Generated by CustomAssertionGenerator.
 * Although this class is not final to allow Soft assertions proxy, if you wish
 * to extend it, extend {@link AbstractFeatureAssert} instead.
 */
public class FeatureAssert extends AbstractFeatureAssert<FeatureAssert, Feature> {

	/**
	 * Creates a new <code>{@link FeatureAssert}</code> to make assertions on
	 * actual Feature.
	 *
	 * @param actual the Feature we want to make assertions on.
	 */
	public FeatureAssert(Feature actual) {
		super(actual, FeatureAssert.class);
	}

	/**
	 * An entry point for FeatureAssert to follow AssertJ standard
	 * <code>assertThat()</code> statements.<br>
	 * With a static import, one can write directly:
	 * <code>assertThat(myFeature)</code> and get specific assertion with code
	 * completion.
	 *
	 * @param actual the Feature we want to make assertions on.
	 * @return a new <code>{@link FeatureAssert}</code>
	 */
	@org.assertj.core.util.CheckReturnValue
	public static FeatureAssert assertThat(Feature actual) {
		return new FeatureAssert(actual);
	}
}
