ROOT = ../../../../../..

NAME = Activator
PACKAGE = org.osgi.test.cases.startlevel.tb3
VERSION = 1.0
DESC = "Start level test bundle 3"
ON_TARGET	= true

SOURCES = \
	Activator.java

include $(ROOT)/cnf/testbundle.mk
