ROOT = ../../../..

VERSION = 1
NAME	= csv2xml
PACKAGE = org.osgi.tools.csv2xml

SOURCES = \
	csv2xml.java

BTOOL   = \
	-property version $(VERSION)  \
	-property main    $(NAME) \
	-property package $(PACKAGE) \
	-manifest Manifest.mf


include $(ROOT)/cnf/package.mk
