/*
 * Copyright (c) OSGi Alliance (2001, 2008). All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.w3c.dom.css;
public abstract interface CSS2Properties {
	public abstract java.lang.String getAzimuth();
	public abstract java.lang.String getBackground();
	public abstract java.lang.String getBackgroundAttachment();
	public abstract java.lang.String getBackgroundColor();
	public abstract java.lang.String getBackgroundImage();
	public abstract java.lang.String getBackgroundPosition();
	public abstract java.lang.String getBackgroundRepeat();
	public abstract java.lang.String getBorder();
	public abstract java.lang.String getBorderBottom();
	public abstract java.lang.String getBorderBottomColor();
	public abstract java.lang.String getBorderBottomStyle();
	public abstract java.lang.String getBorderBottomWidth();
	public abstract java.lang.String getBorderCollapse();
	public abstract java.lang.String getBorderColor();
	public abstract java.lang.String getBorderLeft();
	public abstract java.lang.String getBorderLeftColor();
	public abstract java.lang.String getBorderLeftStyle();
	public abstract java.lang.String getBorderLeftWidth();
	public abstract java.lang.String getBorderRight();
	public abstract java.lang.String getBorderRightColor();
	public abstract java.lang.String getBorderRightStyle();
	public abstract java.lang.String getBorderRightWidth();
	public abstract java.lang.String getBorderSpacing();
	public abstract java.lang.String getBorderStyle();
	public abstract java.lang.String getBorderTop();
	public abstract java.lang.String getBorderTopColor();
	public abstract java.lang.String getBorderTopStyle();
	public abstract java.lang.String getBorderTopWidth();
	public abstract java.lang.String getBorderWidth();
	public abstract java.lang.String getBottom();
	public abstract java.lang.String getCaptionSide();
	public abstract java.lang.String getClear();
	public abstract java.lang.String getClip();
	public abstract java.lang.String getColor();
	public abstract java.lang.String getContent();
	public abstract java.lang.String getCounterIncrement();
	public abstract java.lang.String getCounterReset();
	public abstract java.lang.String getCssFloat();
	public abstract java.lang.String getCue();
	public abstract java.lang.String getCueAfter();
	public abstract java.lang.String getCueBefore();
	public abstract java.lang.String getCursor();
	public abstract java.lang.String getDirection();
	public abstract java.lang.String getDisplay();
	public abstract java.lang.String getElevation();
	public abstract java.lang.String getEmptyCells();
	public abstract java.lang.String getFont();
	public abstract java.lang.String getFontFamily();
	public abstract java.lang.String getFontSize();
	public abstract java.lang.String getFontSizeAdjust();
	public abstract java.lang.String getFontStretch();
	public abstract java.lang.String getFontStyle();
	public abstract java.lang.String getFontVariant();
	public abstract java.lang.String getFontWeight();
	public abstract java.lang.String getHeight();
	public abstract java.lang.String getLeft();
	public abstract java.lang.String getLetterSpacing();
	public abstract java.lang.String getLineHeight();
	public abstract java.lang.String getListStyle();
	public abstract java.lang.String getListStyleImage();
	public abstract java.lang.String getListStylePosition();
	public abstract java.lang.String getListStyleType();
	public abstract java.lang.String getMargin();
	public abstract java.lang.String getMarginBottom();
	public abstract java.lang.String getMarginLeft();
	public abstract java.lang.String getMarginRight();
	public abstract java.lang.String getMarginTop();
	public abstract java.lang.String getMarkerOffset();
	public abstract java.lang.String getMarks();
	public abstract java.lang.String getMaxHeight();
	public abstract java.lang.String getMaxWidth();
	public abstract java.lang.String getMinHeight();
	public abstract java.lang.String getMinWidth();
	public abstract java.lang.String getOrphans();
	public abstract java.lang.String getOutline();
	public abstract java.lang.String getOutlineColor();
	public abstract java.lang.String getOutlineStyle();
	public abstract java.lang.String getOutlineWidth();
	public abstract java.lang.String getOverflow();
	public abstract java.lang.String getPadding();
	public abstract java.lang.String getPaddingBottom();
	public abstract java.lang.String getPaddingLeft();
	public abstract java.lang.String getPaddingRight();
	public abstract java.lang.String getPaddingTop();
	public abstract java.lang.String getPage();
	public abstract java.lang.String getPageBreakAfter();
	public abstract java.lang.String getPageBreakBefore();
	public abstract java.lang.String getPageBreakInside();
	public abstract java.lang.String getPause();
	public abstract java.lang.String getPauseAfter();
	public abstract java.lang.String getPauseBefore();
	public abstract java.lang.String getPitch();
	public abstract java.lang.String getPitchRange();
	public abstract java.lang.String getPlayDuring();
	public abstract java.lang.String getPosition();
	public abstract java.lang.String getQuotes();
	public abstract java.lang.String getRichness();
	public abstract java.lang.String getRight();
	public abstract java.lang.String getSize();
	public abstract java.lang.String getSpeak();
	public abstract java.lang.String getSpeakHeader();
	public abstract java.lang.String getSpeakNumeral();
	public abstract java.lang.String getSpeakPunctuation();
	public abstract java.lang.String getSpeechRate();
	public abstract java.lang.String getStress();
	public abstract java.lang.String getTableLayout();
	public abstract java.lang.String getTextAlign();
	public abstract java.lang.String getTextDecoration();
	public abstract java.lang.String getTextIndent();
	public abstract java.lang.String getTextShadow();
	public abstract java.lang.String getTextTransform();
	public abstract java.lang.String getTop();
	public abstract java.lang.String getUnicodeBidi();
	public abstract java.lang.String getVerticalAlign();
	public abstract java.lang.String getVisibility();
	public abstract java.lang.String getVoiceFamily();
	public abstract java.lang.String getVolume();
	public abstract java.lang.String getWhiteSpace();
	public abstract java.lang.String getWidows();
	public abstract java.lang.String getWidth();
	public abstract java.lang.String getWordSpacing();
	public abstract java.lang.String getZIndex();
	public abstract void setAzimuth(java.lang.String var0);
	public abstract void setBackground(java.lang.String var0);
	public abstract void setBackgroundAttachment(java.lang.String var0);
	public abstract void setBackgroundColor(java.lang.String var0);
	public abstract void setBackgroundImage(java.lang.String var0);
	public abstract void setBackgroundPosition(java.lang.String var0);
	public abstract void setBackgroundRepeat(java.lang.String var0);
	public abstract void setBorder(java.lang.String var0);
	public abstract void setBorderBottom(java.lang.String var0);
	public abstract void setBorderBottomColor(java.lang.String var0);
	public abstract void setBorderBottomStyle(java.lang.String var0);
	public abstract void setBorderBottomWidth(java.lang.String var0);
	public abstract void setBorderCollapse(java.lang.String var0);
	public abstract void setBorderColor(java.lang.String var0);
	public abstract void setBorderLeft(java.lang.String var0);
	public abstract void setBorderLeftColor(java.lang.String var0);
	public abstract void setBorderLeftStyle(java.lang.String var0);
	public abstract void setBorderLeftWidth(java.lang.String var0);
	public abstract void setBorderRight(java.lang.String var0);
	public abstract void setBorderRightColor(java.lang.String var0);
	public abstract void setBorderRightStyle(java.lang.String var0);
	public abstract void setBorderRightWidth(java.lang.String var0);
	public abstract void setBorderSpacing(java.lang.String var0);
	public abstract void setBorderStyle(java.lang.String var0);
	public abstract void setBorderTop(java.lang.String var0);
	public abstract void setBorderTopColor(java.lang.String var0);
	public abstract void setBorderTopStyle(java.lang.String var0);
	public abstract void setBorderTopWidth(java.lang.String var0);
	public abstract void setBorderWidth(java.lang.String var0);
	public abstract void setBottom(java.lang.String var0);
	public abstract void setCaptionSide(java.lang.String var0);
	public abstract void setClear(java.lang.String var0);
	public abstract void setClip(java.lang.String var0);
	public abstract void setColor(java.lang.String var0);
	public abstract void setContent(java.lang.String var0);
	public abstract void setCounterIncrement(java.lang.String var0);
	public abstract void setCounterReset(java.lang.String var0);
	public abstract void setCssFloat(java.lang.String var0);
	public abstract void setCue(java.lang.String var0);
	public abstract void setCueAfter(java.lang.String var0);
	public abstract void setCueBefore(java.lang.String var0);
	public abstract void setCursor(java.lang.String var0);
	public abstract void setDirection(java.lang.String var0);
	public abstract void setDisplay(java.lang.String var0);
	public abstract void setElevation(java.lang.String var0);
	public abstract void setEmptyCells(java.lang.String var0);
	public abstract void setFont(java.lang.String var0);
	public abstract void setFontFamily(java.lang.String var0);
	public abstract void setFontSize(java.lang.String var0);
	public abstract void setFontSizeAdjust(java.lang.String var0);
	public abstract void setFontStretch(java.lang.String var0);
	public abstract void setFontStyle(java.lang.String var0);
	public abstract void setFontVariant(java.lang.String var0);
	public abstract void setFontWeight(java.lang.String var0);
	public abstract void setHeight(java.lang.String var0);
	public abstract void setLeft(java.lang.String var0);
	public abstract void setLetterSpacing(java.lang.String var0);
	public abstract void setLineHeight(java.lang.String var0);
	public abstract void setListStyle(java.lang.String var0);
	public abstract void setListStyleImage(java.lang.String var0);
	public abstract void setListStylePosition(java.lang.String var0);
	public abstract void setListStyleType(java.lang.String var0);
	public abstract void setMargin(java.lang.String var0);
	public abstract void setMarginBottom(java.lang.String var0);
	public abstract void setMarginLeft(java.lang.String var0);
	public abstract void setMarginRight(java.lang.String var0);
	public abstract void setMarginTop(java.lang.String var0);
	public abstract void setMarkerOffset(java.lang.String var0);
	public abstract void setMarks(java.lang.String var0);
	public abstract void setMaxHeight(java.lang.String var0);
	public abstract void setMaxWidth(java.lang.String var0);
	public abstract void setMinHeight(java.lang.String var0);
	public abstract void setMinWidth(java.lang.String var0);
	public abstract void setOrphans(java.lang.String var0);
	public abstract void setOutline(java.lang.String var0);
	public abstract void setOutlineColor(java.lang.String var0);
	public abstract void setOutlineStyle(java.lang.String var0);
	public abstract void setOutlineWidth(java.lang.String var0);
	public abstract void setOverflow(java.lang.String var0);
	public abstract void setPadding(java.lang.String var0);
	public abstract void setPaddingBottom(java.lang.String var0);
	public abstract void setPaddingLeft(java.lang.String var0);
	public abstract void setPaddingRight(java.lang.String var0);
	public abstract void setPaddingTop(java.lang.String var0);
	public abstract void setPage(java.lang.String var0);
	public abstract void setPageBreakAfter(java.lang.String var0);
	public abstract void setPageBreakBefore(java.lang.String var0);
	public abstract void setPageBreakInside(java.lang.String var0);
	public abstract void setPause(java.lang.String var0);
	public abstract void setPauseAfter(java.lang.String var0);
	public abstract void setPauseBefore(java.lang.String var0);
	public abstract void setPitch(java.lang.String var0);
	public abstract void setPitchRange(java.lang.String var0);
	public abstract void setPlayDuring(java.lang.String var0);
	public abstract void setPosition(java.lang.String var0);
	public abstract void setQuotes(java.lang.String var0);
	public abstract void setRichness(java.lang.String var0);
	public abstract void setRight(java.lang.String var0);
	public abstract void setSize(java.lang.String var0);
	public abstract void setSpeak(java.lang.String var0);
	public abstract void setSpeakHeader(java.lang.String var0);
	public abstract void setSpeakNumeral(java.lang.String var0);
	public abstract void setSpeakPunctuation(java.lang.String var0);
	public abstract void setSpeechRate(java.lang.String var0);
	public abstract void setStress(java.lang.String var0);
	public abstract void setTableLayout(java.lang.String var0);
	public abstract void setTextAlign(java.lang.String var0);
	public abstract void setTextDecoration(java.lang.String var0);
	public abstract void setTextIndent(java.lang.String var0);
	public abstract void setTextShadow(java.lang.String var0);
	public abstract void setTextTransform(java.lang.String var0);
	public abstract void setTop(java.lang.String var0);
	public abstract void setUnicodeBidi(java.lang.String var0);
	public abstract void setVerticalAlign(java.lang.String var0);
	public abstract void setVisibility(java.lang.String var0);
	public abstract void setVoiceFamily(java.lang.String var0);
	public abstract void setVolume(java.lang.String var0);
	public abstract void setWhiteSpace(java.lang.String var0);
	public abstract void setWidows(java.lang.String var0);
	public abstract void setWidth(java.lang.String var0);
	public abstract void setWordSpacing(java.lang.String var0);
	public abstract void setZIndex(java.lang.String var0);
}

