<script name="cmpn-compliance" version="4.0">
	<delay duration="10" type="sec"/>
	<separate duration="1" type="sec"/>
	
	<testcase>test.cm</testcase> 					<!-- Tests the Configuration Management service -->
	<testcase>test.component</testcase> 			<!-- Tests the Declarative Services -->
	<testcase>test.device</testcase> 				<!-- Tests the Device Access Specification --> 
	<testcase>test.event</testcase> 				<!-- Tests the Event Admin --> 
	<testcase>test.http</testcase> 					<!-- Tests the Http Service -->
	<testcase>test.io</testcase> 					<!-- Tests IO Service (generic conncetion framework) -->
	<testcase>test.log</testcase> 					<!-- Tests the Log Service -->
	<testcase>test.measurement</testcase> 			<!-- Tests the measurement utility -->
	<testcase>test.metatype</testcase> 			    <!-- Tests the metatype spec -->
	<testcase>test.position</testcase> 				<!-- Tests the Position utility -->
	<testcase>test.prefs</testcase> 				<!-- Tests the Preferences service -->
	<testcase>test.provisioning</testcase> 			<!-- Tests Initial Provisioning -->
	<testcase>test.signature.cmpn</testcase>		<!-- Tests the API signatures -->
	<testcase>test.tracker</testcase> 		        <!-- The service tracker test case -->
	<testcase>test.upnp</testcase> 		       		<!-- The service tracker test case -->
	<testcase>test.useradmin</testcase> 			<!-- Tests the UserAdmin service -->
	<testcase>test.wireadmin</testcase> 			<!-- Tests the Wire Admin Service -->
	<testcase>test.xml</testcase> 					<!-- Tests the XML Parser Service -->	
</script>

