<script name="core-compliance" version="4.1">
	<delay duration="10" type="sec"/>
	<separate duration="1" type="sec"/>
	
	<testcase>test.framework.classloading</testcase>
	<testcase>test.framework.classpath</testcase>
	<testcase>test.framework.div</testcase>
	<testcase>test.framework.dynpkgimport</testcase>
	<testcase>test.framework.filter</testcase>
	<testcase>test.framework.fragments</testcase>
	<testcase>test.framework.lifecycle</testcase>
	<testcase>test.framework.registry</testcase>
	<testcase>test.framework.syncbundlelistener</testcase>
	<testcase>test.packageadmin.tc1</testcase>
	<testcase>test.packageadmin.tc2</testcase>
	<testcase>test.packageadmin.tc3</testcase>
	<testcase>test.packageadmin.tc5</testcase>
	<testcase>test.permissionadmin.conditional</testcase>
	<testcase>test.permissionadmin.main</testcase>
	<testcase>test.permissionadmin.nosecurity</testcase>
	<testcase>test.permissionadmin.security</testcase>
	<testcase>test.permissionadmin.signature</testcase>
	<testcase>test.signature.core</testcase>
	<testcase>test.startlevel</testcase>
	<testcase>test.url</testcase>
</script>

