<script name="meg-compliance" version="4.0">
	<delay duration="2" type="sec"/>
	<separate duration="1" type="sec"/>
	
	<!-- <testcase>test.application</testcase> 					Tests the Configuration Management service -->
	<testcase>test.cm</testcase> 					<!-- Tests the Configuration Management service -->
	<testcase>test.component</testcase> 			<!-- Tests the Declarative Services -->
	<testcase>test.deploymentadmin.tc1</testcase> 	<!-- Tests the Deployment Admin --> 
	<testcase>test.deploymentadmin.tc2</testcase> 	<!-- Tests the Deployment Admin --> 
	<testcase>test.deploymentadmin.mo</testcase> 	<!-- Tests the Deployment Admin Managed Object --> 
	<testcase>test.dmt.main</testcase> 				<!-- Tests the Dmt Main functionality --> 
	<testcase>test.dmt.plugins</testcase> 			<!-- Tests the Dmt Plugin functionality --> 
	<testcase>test.event</testcase> 				<!-- Tests the Event Admin --> 
	<testcase>test.io</testcase> 					<!-- Tests IO Service (generic conncetion framework) -->
	<testcase>test.log</testcase> 					<!-- Tests the Log Service -->
	<testcase>test.metatype</testcase> 			    <!-- Tests the metatype spec -->
	<testcase>test.monitor</testcase> 			    <!-- Tests the Monitor spec -->
	<testcase>test.policy</testcase> 				<!-- Tests the Policy (gsm/mobile conditions) -->
	<testcase>test.prefs</testcase> 				<!-- Tests the Preferences service -->
	<testcase>test.tracker</testcase> 		        <!-- The service tracker test case -->
	<testcase>test.xml</testcase> 					<!-- Tests the XML Parser Service -->	
</script>

