package org.osgi.impl.service.onem2m.serialization;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class LongShortConverter {

	private static final Logger LOGGER = LoggerFactory.getLogger(LongShortConverter.class);

	private static HashMap<String,String> map = new HashMap<String,String>();

	public static String l2s(String longname) {
		String r = map.get(longname);
		if( r == null ) {
			LOGGER.debug("short name is not defined for " + longname);
		}
		return r;
	}

	public static String s2l(String shortname) {
		Set<String> keys = map.keySet();
		String r = null;
		for(String key: keys){
			if(shortname.equals(map.get(key))){
				r = key;
				break;
			}
		}

		if( r == null ) {
			LOGGER.debug("long name is not defined for " + shortname);
		}
		return r;
	}

	static String[] data = {
			"operation", "op",
			"to", "to",
			"from", "fr",
			"requestIdentifier", "rqi",
			"resourceType", "ty",
			"primitiveContent", "pc",
			"roleIDs", "rids",
			"originatingTimestamp", "ot",
			"requestExpirationTimestamp", "rqet",
			"resultExpirationTimestamp", "rset",
			"operationExecutionTime", "oet",
			"responseType", "rt",
			"resultPersistence", "rp",
			"resultContent", "rcn",
			"eventCategory", "ec",
			"deliveryAggregation", "da",
			"groupRequestIdentifier", "gid",
			"filterCriteria", "fc",
			"discoveryResultType", "drt",
			"responseStatusCode", "rsc",
			"tokens", "tkns",
			"tokenIDs", "tids",
			"tokenRequestIndicator", "tqi",
			"localTokenIDs", "ltids",
			"groupRequestTargetMembers", "grtm",
			"assignedTokenIdentifiers", "ati",
			"tokenRequestInformation", "tqf",
			"contentStatus", "cnst",
			"contentOffset", "cnot",
			"authorSignIndicator", "asi",
			"authorSignReqInfo", "asri",
			"authorSigns", "aus",
			"authorRelIndicator", "auri",
			"semanticQueryIndicator", "sqi",
			"releaseVersionIndicator", "rvi",
			"vendorInformation", "vsi",
			"requestPrimitive", "rqp",
			"responsePrimitive", "rsp",
			"accessControlPolicyIDs", "acpi",
			"announcedAttribute", "aa",
			"announceTo", "at",
			"creationTime", "ct",
			"expirationTime", "et",
			"labels", "lbl",
			"lastModifiedTime", "lt",
			"Link", "lnk",
			"parentID", "pi",
			"resourceID", "ri",
			"stateTag", "st",
			"resourceName", "rn",
			"privileges", "pv",
			"selfPrivileges", "pvs",
			"App-ID", "api",
			"AE-ID", "aei",
			"AE-IDList", "ail",
			"appName", "apn",
			"pointOfAccess", "poa",
			"ontologyRef", "or",
			"nodeLink", "nl",
			"contentSerialization", "csz",
			"registrationStatus", "regs",
			"trackRegistrationPoints", "trps",
			"sessionCapabilities", "scp",
			"activityPatternElements", "ape",
			"triggerEnable", "tren",
			"creator", "cr",
			"maxNrOfInstances", "mni",
			"maxByteSize", "mbs",
			"maxInstanceAge", "mia",
			"currentNrOfInstances", "cni",
			"currentByteSize", "cbs",
			"locationID", "li",
			"disableRetrieval", "disr",
			"contentInfo", "cnf",
			"contentSize", "cs",
			"contentRef", "conr",
			"containerDefinition", "cnd",
			"content", "con",
			"cseType", "cst",
			"CSE-ID", "csi",
			"supportedResourceType", "srt",
			"notificationCongestionPolicy", "ncp",
			"source", "sr",
			"target", "tg",
			"lifespan", "ls",
			"eventCat", "ec",
			"deliveryMetaData", "dmd",
			"aggregatedRequest", "arq",
			"eventID", "evi",
			"eventType", "evt",
			"evenStart", "evs",
			"eventEnd", "eve",
			"operationType", "opt",
			"dataSize", "ds",
			"execStatus", "exs",
			"execResult", "exr",
			"execDisable", "exd",
			"execTarget", "ext",
			"execMode", "exm",
			"execFrequency", "exf",
			"execDelay", "exy",
			"execNumber", "exn",
			"execReqArgs", "exra",
			"execEnable", "exe",
			"memberType", "mt",
			"currentNrOfMembers", "cnm",
			"maxNrOfMembers", "mnm",
			"memberIDs", "mid",
			"membersAccessControlPolicyIDs", "macp",
			"memberTypeValidated", "mtv",
			"consistencyStrategy", "csy",
			"semanticSupportIndicator", "ssi",
			"groupName", "gn",
			"locationSource", "los",
			"locationUpdatePeriod", "lou",
			"locationTargetID", "lot",
			"locationServer", "lor",
			"locationContainerID", "loi",
			"locationContainerName", "lon",
			"locationStatus", "lost",
			"authID", "aid",
			"retrieveLastKnownLocation", "rlkl",
			"locationUpdateEventCriteria", "luec",
			"description", "dc",
			"cmdType", "cmt",
			"mgmtDefinition", "mgd",
			"objectIDs", "obis",
			"objectPaths", "obps",
			"mgmtSchema", "mgs",
			"nodeID", "ni",
			"hostedCSELink", "hcl",
			"mgmtClientAddress", "mgca",
			"hostedAELinks", "hael",
			"hostedServiceLinks", "hsl",
			"networkID", "nid",
			"roamingStatus", "rms",
			"CSEBase", "cb",
			"M2M-Ext-ID", "mei",
			"Trigger-Recipient-ID", "tri",
			"requestReachability", "rr",
			"triggerReferenceNumber", "trn",
			"descendantCSEs", "dcse",
			"multicastCapability", "mtcc",
			"originator", "org",
			"metaInformation", "mi",
			"requestStatus", "rs",
			"operationResult", "ors",
			"requestID", "rid",
			"scheduleElement", "se",
			"networkCoordinated", "nco",
			"deviceIdentifier", "di",
			"ruleLinks", "rlk",
			"niddRequired", "nrq",
			"statsCollectID", "sci",
			"collectingEntityID", "cei",
			"collectedEntityID", "cdi",
			"devStatus", "ss",
			"statsRuleStatus", "srs",
			"statModel", "sm",
			"collectPeriod", "cp",
			"eventNotificationCriteria", "enc",
			"expirationCounter", "exc",
			"notificationURI", "nu",
			"groupID", "gpi",
			"notificationForwardingURI", "nfu",
			"batchNotify", "bn",
			"rateLimit", "rl",
			"preSubscriptionNotify", "psn",
			"pendingNotification", "pn",
			"notificationStoragePriority", "nsp",
			"latestNotify", "ln",
			"notificationContentType", "nct",
			"notificationEventCat", "nec",
			"subscriberURI", "su",
			"version", "vr",
			"URL", "url",
			"update", "ud",
			"updateStatus", "uds",
			"install", "in",
			"uninstall", "un",
			"installStatus", "ins",
			"activate", "act",
			"deactivate", "dea",
			"activeStatus", "acts",
			"memAvailable", "mma",
			"memTotal", "mmt",
			"areaNwkType", "ant",
			"listOfDevices", "ldv",
			"devId", "dvd",
			"devType", "dvt",
			"areaNwkId", "awi",
			"sleepInterval", "sli",
			"sleepDuration", "sld",
			"listOfNeighbors", "lnh",
			"batteryLevel", "btl",
			"batteryStatus", "bts",
			"deviceLabel", "dlb",
			"manufacturer", "man",
			"model", "mod",
			"deviceType", "dty",
			"fwVersion", "fwv",
			"swVersion", "swv",
			"hwVersion", "hwv",
			"manufacturerDetailsLink", "mfdl",
			"manufacturingDate", "mfd",
			"subModel", "smod",
			"deviceName", "dvnm",
			"osVersion", "osv",
			"country", "cnty",
			"location", "loc",
			"systemTime", "syst",
			"supportURL", "spur",
			"presentationURL", "purl",
			"protocol", "ptl",
			"capabilityName", "can",
			"attached", "att",
			"capabilityActionStatus", "cas",
			"enable", "ena",
			"disable", "dis",
			"currentState", "cus",
			"reboot", "rbo",
			"factoryReset", "far",
			"logTypeId", "lgt",
			"logData", "lgd",
			"logStatus", "lgst",
			"logStart", "lga",
			"logStop", "lgo",
			"firmwareName", "fwn",
			"softwareName", "swn",
			"cmdhPolicyName", "cpn",
			"mgmtLink", "cmlk",
			"activeCmdhPolicyLink", "acmlk",
			"order", "od",
			"defEcValue", "dev",
			"requestOrigin", "ror",
			"requestContext", "rct",
			"requestContextNotification", "rctn",
			"requestCharacteristics", "rch",
			"applicableEventCategories", "aecs",
			"applicableEventCategory", "aec",
			"defaultRequestExpTime", "dqet",
			"defaultResultExpTime", "dset",
			"defaultOpExecTime", "doet",
			"defaultRespPersistence", "drp",
			"defaultDelAggregation", "dda",
			"limitsEventCategory", "lec",
			"limitsRequestExpTime", "lqet",
			"limitsResultExpTime", "lset",
			"limitsOpExecTime", "loet",
			"limitsRespPersistence", "lrp",
			"limitsDelAggregation", "lda",
			"targetNetwork", "ttn",
			"accessControlPolicy", "acp",
			"accessControlPolicyAnnc", "acpA",
			"AE", "ae",
			"AEAnnc", "aeA",
			"container", "cnt",
			"containerAnnc", "cntA",
			"contentInstance", "cin",
			"contentInstanceAnnc", "cinA",
			"delivery", "dlv",
			"eventConfig", "evcg",
			"execInstance", "exin",
			"group", "grp",
			"groupAnnc", "grpA",
			"locationPolicy", "lcp",
			"locationPolicyAnnc", "lcpA",
			"m2mServiceSubscriptionProfile", "mssp",
			"mgmtCmd", "mgc",
			"node", "nod",
			"nodeAnnc", "nodA",
			"pollingChannel", "pch",
			"remoteCSE", "csr",
			"remoteCSEAnnc", "csrA",
			"request", "req",
			"schedule", "sch",
			"scheduleAnnc", "schA",
			"serviceSubscribedAppRule", "asar",
			"serviceSubscribedNode", "svsn",
			"statsCollect", "stcl",
			"statsConfig", "stcg",
			"subscription", "sub",
			"firmware", "fwr",
			"firmwareAnnc", "fwrA",
			"software", "swr",
			"softwareAnnc", "swrA",
			"memory", "mem",
			"memoryAnnc", "memA",
			"areaNwkInfo", "ani",
			"areaNwkInfoAnnc", "aniA",
			"areaNwkDeviceInfo", "andi",
			"areaNwkDeviceInfoAnnc", "andiA",
			"battery", "bat",
			"batteryAnnc", "batA",
			"deviceInfo", "dvi",
			"deviceInfoAnnc", "dviA",
			"deviceCapability", "dvc",
			"deviceCapabilityAnnc", "dvcA",
			"rebootAnnc", "rboA",
			"eventLog", "evl",
			"eventLogAnnc", "evlA",
			"cmdhPolicy", "cmp",
			"activeCmdhPolicy", "acmp",
			"cmdhDefaults", "cmdf",
			"cmdhDefEcValue", "cmdv",
			"cmdhEcDefParamValues", "cmpv",
			"cmdhLimits", "cml",
			"cmdhNetworkAccessRules", "cmnr",
			"cmdhNwAccessRule", "cmwr",
			"cmdhBuffer", "cmbf",
			"notificationTargetMgmtPolicyRef", "ntpr",
			"notificationTargetPolicy", "ntp",
			"policyDeletionRules", "pdr",
			"dynamicAuthorizationConsultation", "dac",
			"semanticDescriptor", "smd",
			"semanticDescriptorAnnc", "smdA",
			"timeSeries", "ts",
			"timeSeriesAnnc", "tsA",
			"timeSeriesInstance", "tsi",
			"timeSeriesInstanceAnnc", "tsiA",
			"role", "rol",
			"token", "tk",
			"genericInterworkingService", "gis",
			"genericInterworkingServiceAnnc", "gisA",
			"genericInterworkingOperationInstance", "gio",
			"genericInterworkingOperationInstanceAnnc", "gioA",
			"svcObjWrapper", "ajsw",
			"svcObjWrapperAnnc", "ajswA",
			"svcFwWrapper", "ajfw",
			"svcFwWrapperAnnc", "ajfwA",
			"allJoynApp", "ajap",
			"allJoynAppAnnc", "ajapA",
			"allJoynSvcObject", "ajso",
			"allJoynSvcObjectAnnc", "ajsoA",
			"allJoynInterface", "ajif",
			"allJoynInterfaceAnnc", "ajifA",
			"allJoynMethod", "ajmd",
			"allJoynMethodAnnc", "ajmdA",
			"allJoynMethodCall", "ajmc",
			"allJoynMethodCallAnnc", "ajmcA",
			"allJoynProperty", "ajpr",
			"allJoynPropertyAnnc", "ajprA",
			"authorizationDecision", "auds",
			"authorizationPolicy", "aupy",
			"authorizationInformation", "auif",
			"ontologyRepository", "ontr",
			"ontologyRepositoryAnnc", "ontrA",
			"ontology", "ont",
			"ontologyAnnc", "ontA",
			"semanticMashupJobProfile", "smjp",
			"semanticMashupJobProfileAnnc", "smjpA",
			"semanticMashupInstance", "smi",
			"semanticMashupInstanceAnnc", "smiA",
			"semanticMashupResult", "smr",
			"semanticMashupResultAnnc", "smrA",
			"AEContactList", "alst",
			"AEContactListPerCSE", "alpc",
			"localMulticastGroup", "lmg",
			"multimediaSession", "mms",
			"multimediaSessionAnnc", "mmsA",
			"triggerRequest", "tgr",
			"crossResourceSubscription", "crs",
			"createdBefore", "crb",
			"createdAfter", "cra",
			"modifiedSince", "ms",
			"unmodifiedSince", "us",
			"stateTagSmaller", "sts",
			"stateTagBigger", "stb",
			"expireBefore", "exb",
			"expireAfter", "exa",
			"labelsQuery", "lbq",
			"sizeAbove", "sza",
			"sizeBelow", "szb",
			"contentType", "cty",
			"limit", "lim",
			"attribute", "atr",
			"contentFilterSyntax", "cfs",
			"contentFilterQuery", "cfq",
			"level", "lvl",
			"offset", "ofst",
			"notificationEventType", "net",
			"operationMonitor", "om",
			"representation", "rep",
			"filterUsage", "fu",
			"eventCatType", "ect",
			"eventCatNo", "ecn",
			"number", "num",
			"duration", "dur",
			"notification", "sgn",
			"notificationEvent", "nev",
			"verificationRequest", "vrq",
			"subscriptionDeletion", "sud",
			"subscriptionReference", "sur",
			"notificationTarget", "ntt",
			"targetRemovalRequest", "trr",
			"targetRemovalAllowance", "tra",
			"IPEDiscoveryRequest", "idr",
			"AERegistrationPointChange", "aerp",
			"AEReferenceIDChange", "aerid",
			"trackingID1", "tid1",
			"trackingID2", "tid2",
			"operations", "ops",
			"action", "acn",
			"status", "sus",
			"childResource", "ch",
			"accessControlRule", "acr",
			"accessControlOriginators", "acor",
			"accessControlOperations", "acop",
			"accessControlContexts", "acco",
			"accessControWindow", "actw",
			"accessControlIpAddresses", "acip",
			"ipv4Addresses", "ipv4",
			"ipv6Addresses", "ipv6",
			"accessControlLocationRegion", "aclr",
			"countryCode", "accc",
			"circRegion", "accr",
			"name", "nm",
			"specializationID", "spid",
			"value", "val",
			"type", "typ",
			"maxNrOfNotify", "mnn",
			"timeWindow", "tww",
			"scheduleEntry", "sce",
			"aggregatedNotification", "agn",
			"attributeList", "atrl",
			"securityInfo", "seci",
			"aggregatedResponse", "agr",
			"resource", "rce",
			"URIList", "uril",
			"debugInfo", "dbg",
			"queryResult", "qres",
			"anyArg", "any",
			"fileType", "ftyp",
			"URI", "uri",
			"username", "unm",
			"password", "pwd",
			"filesize", "fsi",
			"targetFile", "tgf",
			"delaySeconds", "dss",
			"successURL", "surl",
			"startTime", "stt",
			"completeTime", "cpt",
			"UUID", "uuid",
			"executionEnvRef", "eer",
			"reset", "rst",
			"upload", "uld",
			"download", "dld",
			"softwareInstall", "swin",
			"softwareUpdate", "swup",
			"softwareUninstall", "swun",
			"tracingOption", "tcop",
			"tracingInfo", "tcin",
			"responseTypeValue", "rtv",
			"timeOfDay", "tod",
			"locationRegions", "lr",
			"URIReference", "urir",
			"semanticsFilter", "smf",
			"missingDataList", "mdl",
			"missingData", "md",
			"tokenID", "tkid",
			"holder", "tkhd",
			"issuer", "tkis",
			"permission", "pm",
			"resourceIDs", "ris",
			"localTokenIdAssignment", "ltia",
			"localTokenID", "lti",
			"dasInfo", "dasi",
			"dasRequest", "daq",
			"securedDasRequest", "sdr",
			"filterOperation", "fo",
			"targetedResourceType", "trt",
			"ipv4Address", "ip4",
			"ipv6Address", "ip6",
			"originatorRoleIDs", "orid",
			"requestTimestamp", "rts",
			"targetedResourceID", "trid",
			"proposedPrivilegesLifetime", "ppl",
			"roleIDsFromACPs", "rfa",
			"dynamicACPInfo", "dai",
			"grantedPrivileges", "gp",
			"privilegesLifetime", "pl",
			"securityInfoType", "sit",
			"dasResponse", "dres",
			"dynAuthRelMapRequest", "darq",
			"dynAuthRelMapResponse", "dars",
			"esprimRandObject", "ero",
			"esprimObject", "epo",
			"escertkeMessage", "eckm",
			"resourceRef", "rrf",
			"resourceRefList", "rrl",
			"esprimRandID", "esri",
			"esprimRandValue", "esrv",
			"esprimRandExpiry", "esrx",
			"esprimKeyGenAlgID", "esk",
			"esprimKeyGenAlgIDs", "esks",
			"esprimProtocolAndAlgIDs", "espa",
			"supportede2ESecFeatures", "esf",
			"certificates", "escert",
			"sharedReceiverESPrimRandObject", "esro",
			"networkAction", "nwa",
			"initialBackoffTime", "ibt",
			"additionalBackoffTime", "abt",
			"maximumBackoffTime", "mbt",
			"optionalRandomBackoffTime", "rbt",
			"backOffParametersSet", "bops",
			"dataLink", "dali",
			"attributeName", "atn",
			"dataContainerID", "dcid",
			"accessControlAuthenticationFlag", "acaf",
			"accessControlObjectDetails", "acod",
			"dataLinkEntry", "dle",
			"childResourceType", "chty",
			"parentResourceType", "pty",
			"childLabels", "clbl",
			"parentLabels", "palb",
			"childAttribute", "catr",
			"parentAttribute", "patr",
			"applyRelativePath", "arp",
			"sessionDescription", "sdc",
			"activityPattern", "apt",
			"stationaryIndication", "sti",
			"dataSizeIndicator", "dsi",
			"eventNotificationCriteriaEntry", "encn",
			"latest", "la",
			"oldest", "ol",
	};

	static {
		int l = data.length;
		for(int i=0;i<l;i++) {
			if(data[i].contains(" ")) {
				LOGGER.debug("" + i +":"+ data[i] + "contains space");

			}
			if(data[i].contains("*")) {
				LOGGER.debug("" + i +":"+ data[i] + "contains *");
			}
		}

		HashSet<String> shortset = new HashSet<String>();
		for(int i=0;i<l/2;i++) {

			String longname = data[i*2];
			String shortname = data[i*2+1];

			if( shortset.contains(shortname) ) {
				LOGGER.debug("shortname "+ shortname + " is duplicated.");
			}
			shortset.add(shortname);

			if ( map.get(longname) != null ) {
				LOGGER.debug(longname +" is duplicated. #line:"+(i+21) );
			}
			map.put(data[i*2],data[i*2+1]);
		}
	}
}
