/*
 * Copyright (c) OSGi Alliance (2016). All Rights Reserved.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.osgi.service.zigbee;

/**
 * The {@code ZigBeeDataOutput} interface is designed for converting java data
 * types into a series of bytes. The purpose of this interface is the same as
 * the DataOutput interface provided by java, with the difference that in this
 * interface, the generated bytes ordering is little endian, whereas in the
 * DataOutput is big endian.
 * 
 * @author $Id$
 */
public interface ZigBeeDataOutput {

	/**
	 * Appends a byte to the data output
	 * 
	 * @param value The value to append
	 */
	public void writeByte(byte value);

	/**
	 * Appends an int value to the data output.
	 * 
	 * @param value The int value to append
	 * @param size The size in bytes that have to be actually appended. The size
	 *        must be in the range (1,4]
	 */
	public void writeInt(int value, int size);

	/**
	 * Appends a long to to the data output.
	 * 
	 * @param value The long value to append
	 * @param size The size in bytes that have to be actually appended.
	 */
	public void writeLong(long value, int size);

	/**
	 * Appends on the Data Output Stream a float value
	 * 
	 * @param value The float value to append
	 * @param size The size in bytes that have to be actually appended.
	 */
	public void writeFloat(float value, int size);

	/**
	 * Appends on the Data Output Stream a double value
	 * 
	 * @param value The double value to append
	 */
	public void writeDouble(double value);

	/**
	 * Appends on the Data Output Stream a bytes value
	 * 
	 * @param bytes The bytes value to append
	 * @param length The length in bytes that have to be actually appended.
	 */
	public void writeBytes(byte[] bytes, int length);

}
