/*
 * Copyright (c) OSGi Alliance (2013). All Rights Reserved.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.osgi.service.zigbee;

/**
 * This interface represents events generated by a ZigBee Device node
 * 
 * @version 1.0
 */
public interface ZigBeeEvent {

	/**
	 * @return The cluster object concerned by the events
	 */
	public ZCLCluster getCluster();

	/**
	 * @return An object containing the new value for the ZigBee attribute that
	 *         has changed.
	 */
	public Object getValue();

}
