# The dll file in this directory is built using MS Visual C++ 6.0 using the
# following steps:
#
# Create a new Win32 Dynamic Link Library project.
#
# Add the file NativeCodeI.c to the project.
#
# Add the java JNI include directories to the "additional include directories"
# setting for Win32 Release, tab C/C++, category preprocessor. In my case, I added
# C:\jdk1.2.2\include;C:\jdk1.2.2\include\Win32.
# 
# Set active configuration to Dll - Win32 Release.
#
# Build the dll.
all: 
	echo See comments in this file

