@startuml
hide footbox
skinparam monochrome true
skinparam defaultFontName ProductusOSGiBookc
skinparam shadowing false

participant Webserver as wb
participant ApplicationCondition as c
participant "Servlet 1" as ll
participant "Servlet 2" as rl

activate ll
activate c
ll -> c: addServlet1
ll -> wb: addServlet1
activate wb
activate rl
rl -> c: addServlet2
rl -> wb: addServlet2
c -> wb: setApplicationConditon
activate wb
wb -> wb: StartListening
@enduml