@startuml
hide footbox
skinparam monochrome true
skinparam defaultFontName ProductusOSGiBookc
skinparam shadowing false

participant Webserver as wb
participant "Servlet 1" as ll
participant "Servlet 2" as rl

activate wb
wb -> wb: startListening
activate ll
ll -> wb: addServlet
activate rl
rl -> wb: addServlet
@enduml