/*
 * Copyright (c) OSGi Alliance (2012, 2016). All Rights Reserved.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.osgi.service.jaxrs.runtime.dto;

import org.osgi.dto.DTO;
import org.osgi.resource.dto.ResourceDTO;
import org.osgi.service.jaxrs.whiteboard.JaxRSWhiteboardConstants;

/**
 * Represents common information about a JAX-RS resource service.
 *
 * @NotThreadSafe
 * @author $Id$
 */
public abstract class ApplicationDTO extends DTO {
	/**
	 * The name of the resource. This can be set set using the
	 * {@link JaxRSWhiteboardConstants#JAX_RS_NAME} property, otherwise it is
	 * automatically generated by the runtime
	 */
	public String					name;

	/**
	 * The base URI of the resource defined by
	 * {@link JaxRSWhiteboardConstants#JAX_RS_APPLICATION_BASE}.
	 */
	public String					base;

	/**
	 * The RequestPaths handled by statically defined resources in this
	 * Application
	 */
	public ResourceMethodInfoDTO[]	resourceMethods;

	/**
	 * Returns the representations of the dynamic JAX-RS resource services
	 * associated with this Application. The returned array may be empty if this
	 * application is currently not associated with any JAX-RS Resource
	 * services.
	 */
	public ResourceDTO[]			resourceDTOs;

	/**
	 * Returns the representations of the dynamic JAX-RS extension services
	 * associated with this Application. The returned array may be empty if this
	 * application is currently not associated with any JAX-RS extension
	 * services.
	 */
	public ExtensionDTO[]			extensionDTOs;

	/**
	 * Service property identifying the JAX-RS application service
	 */
	public long						serviceId;
}
