<script name="mobile-compliance" version="4.1">
	<delay duration="10" type="sec"/>
	<properties location="test.properties"/>
	<separate duration="1" type="sec"/>
	
	<testcase>test.application</testcase> 			<!-- Tests the Configuration Management service -->
	<testcase>test.cm</testcase> 					<!-- Tests the Configuration Management service -->
	<testcase>test.component</testcase> 			<!-- Tests the Declarative Services -->
	<testcase>test.deploymentadmin.tc1</testcase> 	<!-- Tests the Deployment Admin --> 
	<testcase>test.deploymentadmin.tc2</testcase> 	<!-- Tests the Deployment Admin --> 
	<testcase>test.deploymentadmin.mo</testcase> 	<!-- Tests the Deployment Admin Managed Object --> 
	<testcase>test.dmt.tc1</testcase> 				<!-- Tests the Dmt Main functionality --> 
	<testcase>test.dmt.tc2</testcase> 				<!-- Tests the Dmt Plugin functionality --> 
	<testcase>test.dmt.tc3</testcase> 			`	<!-- Tests the Dmt Other functionality --> 
	<testcase>test.event</testcase> 				<!-- Tests the Event Admin --> 
	<testcase>test.io</testcase> 					<!-- Tests IO Service (generic conncetion framework) -->
	<testcase>test.log</testcase> 					<!-- Tests the Log Service -->
	<testcase>test.metatype</testcase> 			    <!-- Tests the metatype spec -->
	<testcase>test.monitor</testcase> 			    <!-- Tests the Monitor spec -->
	<testcase>test.policy</testcase> 				<!-- Tests the Policy (gsm/mobile conditions) -->
	<testcase>test.prefs</testcase> 				<!-- Tests the Preferences service -->
	<testcase>test.signature.mobile</testcase>		<!-- Tests the API signatures -->
	<testcase>test.tracker</testcase> 		        <!-- The service tracker test case -->
	<testcase>test.xml</testcase> 					<!-- Tests the XML Parser Service -->	
</script>

