/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_osgi_test_cases_div_tb12_NativeCode */

#ifndef _Included_org_osgi_test_cases_div_tb12_NativeCode
#define _Included_org_osgi_test_cases_div_tb12_NativeCode
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: initOk */
/*
 * Class:     org_osgi_test_cases_div_tb12_NativeCode
 * Method:    count
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_osgi_test_cases_div_tb12_NativeCode_count
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
