/*******************************************************************************
 * Copyright (c) Contributors to the Eclipse Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 *******************************************************************************/

package org.osgi.test.cases.typedevent.junit;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import static org.osgi.test.common.dictionary.Dictionaries.dictionaryOf;

import java.util.HashMap;
import java.util.Map;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.osgi.framework.BundleContext;
import org.osgi.service.typedevent.TypedEventBus;
import org.osgi.service.typedevent.TypedEventConstants;
import org.osgi.service.typedevent.TypedEventHandler;
import org.osgi.service.typedevent.TypedEventPublisher;
import org.osgi.service.typedevent.UntypedEventHandler;
import org.osgi.test.cases.typedevent.common.EventA;
import org.osgi.test.cases.typedevent.common.EventB;
import org.osgi.test.cases.typedevent.common.TypedEventHandlerA;
import org.osgi.test.common.annotation.InjectBundleContext;
import org.osgi.test.common.annotation.InjectService;
import org.osgi.test.junit5.context.BundleContextExtension;
import org.osgi.test.junit5.service.ServiceExtension;

@ExtendWith(BundleContextExtension.class)
@ExtendWith(ServiceExtension.class)
@DisplayName("157.3.4 Typed Event Publishers")
public class TypedEventPublisherTest {

	@InjectBundleContext
	BundleContext context;

	@InjectService
	TypedEventBus eventBus;

	protected static final String TOPIC_A = EventA.class.getName()
			.replace(".", "/");
	protected static final String TOPIC_B = EventB.class.getName()
			.replace(".", "/");

	@DisplayName("157.3.1 Creating Publishers")
	@Nested
	class CreatingPublishersTest {

		@Test
		public void createPublisherWithAutoGeneratedTopic() {
			TypedEventPublisher<EventA> publisher = eventBus
					.createPublisher(EventA.class);

			assertThat(publisher).isNotNull();
			assertThat(publisher.isOpen()).isTrue();
			assertThat(publisher.getTopic()).isEqualTo(TOPIC_A);

			publisher.close();
		}

		@Test
		public void createPublisherWithExplicitTopic() {
			String customTopic = "custom/topic";
			TypedEventPublisher<EventA> publisher = eventBus
					.createPublisher(customTopic, EventA.class);

			assertThat(publisher).isNotNull();
			assertThat(publisher.isOpen()).isTrue();
			assertThat(publisher.getTopic()).isEqualTo(customTopic);

			publisher.close();
		}

		@Test
		public void createUntypedPublisher() {
			String topic = "untyped/topic";
			TypedEventPublisher<Object> publisher = eventBus
					.createPublisher(topic);

			assertThat(publisher).isNotNull();
			assertThat(publisher.isOpen()).isTrue();
			assertThat(publisher.getTopic()).isEqualTo(topic);

			publisher.close();
		}

		@Test
		public void createMultiplePublishersForSameTopic() {
			TypedEventPublisher<EventA> publisher1 = eventBus
					.createPublisher(EventA.class);
			TypedEventPublisher<EventA> publisher2 = eventBus
					.createPublisher(EventA.class);

			assertThat(publisher1).isNotNull();
			assertThat(publisher2).isNotNull();
			assertThat(publisher1).isNotSameAs(publisher2);
			assertThat(publisher1.getTopic()).isEqualTo(publisher2.getTopic());

			publisher1.close();
			publisher2.close();
		}

		@Test
		public void createPublishersForDifferentTopics() {
			TypedEventPublisher<EventA> publisherA = eventBus
					.createPublisher(EventA.class);
			TypedEventPublisher<EventB> publisherB = eventBus
					.createPublisher(EventB.class);

			assertThat(publisherA.getTopic()).isNotEqualTo(publisherB.getTopic());
			assertThat(publisherA.getTopic()).isEqualTo(TOPIC_A);
			assertThat(publisherB.getTopic()).isEqualTo(TOPIC_B);

			publisherA.close();
			publisherB.close();
		}
	}

	@DisplayName("157.3.2 Delivering Events via Publisher")
	@Nested
	class DeliveringEventsTest {

		@Test
		public void deliverTypedEventViaPublisher() {
			TypedEventPublisher<EventA> publisher = eventBus
					.createPublisher(EventA.class);

			TypedEventHandler<EventA> handler = mock(TypedEventHandlerA.class);
			context.registerService(TypedEventHandler.class, handler,
					dictionaryOf(TypedEventConstants.TYPED_EVENT_TYPE,
							EventA.class.getName()));

			EventA event = new EventA();
			event.a = "test";
			publisher.deliver(event);

			verify(handler, timeout(1000)).notify(eq(TOPIC_A),
					any(EventA.class));

			publisher.close();
		}

		@Test
		public void deliverUntypedEventViaTypedPublisher() {
			TypedEventPublisher<EventA> publisher = eventBus
					.createPublisher(EventA.class);

			UntypedEventHandler handler = mock(UntypedEventHandler.class);
			context.registerService(UntypedEventHandler.class, handler,
					dictionaryOf(TypedEventConstants.TYPED_EVENT_TOPICS,
							TOPIC_A));

			Map<String, Object> event = new HashMap<>();
			event.put("a", "test");
			publisher.deliverUntyped(event);

			verify(handler, timeout(1000)).notifyUntyped(eq(TOPIC_A), any());

			publisher.close();
		}

		@Test
		public void deliverViaUntypedPublisher() {
			String topic = "untyped/topic";
			TypedEventPublisher<Object> publisher = eventBus
					.createPublisher(topic);

			UntypedEventHandler handler = mock(UntypedEventHandler.class);
			context.registerService(UntypedEventHandler.class, handler,
					dictionaryOf(TypedEventConstants.TYPED_EVENT_TOPICS, topic));

			Map<String, Object> event = new HashMap<>();
			event.put("key", "value");
			publisher.deliverUntyped(event);

			verify(handler, timeout(1000)).notifyUntyped(eq(topic), any());

			publisher.close();
		}

		@Test
		public void deliverMultipleEventsInOrder() {
			TypedEventPublisher<EventA> publisher = eventBus
					.createPublisher(EventA.class);

			TypedEventHandler<EventA> handler = mock(TypedEventHandlerA.class);
			context.registerService(TypedEventHandler.class, handler,
					dictionaryOf(TypedEventConstants.TYPED_EVENT_TYPE,
							EventA.class.getName()));

			EventA event1 = new EventA();
			event1.a = "first";
			EventA event2 = new EventA();
			event2.a = "second";
			EventA event3 = new EventA();
			event3.a = "third";

			publisher.deliver(event1);
			publisher.deliver(event2);
			publisher.deliver(event3);

			verify(handler, timeout(1000).times(3)).notify(eq(TOPIC_A),
					any(EventA.class));

			publisher.close();
		}

		@Test
		public void deliverEventToExplicitTopic() {
			String customTopic = "custom/event/topic";
			TypedEventPublisher<EventA> publisher = eventBus
					.createPublisher(customTopic, EventA.class);

			UntypedEventHandler handler = mock(UntypedEventHandler.class);
			context.registerService(UntypedEventHandler.class, handler,
					dictionaryOf(TypedEventConstants.TYPED_EVENT_TOPICS,
							customTopic));

			EventA event = new EventA();
			event.a = "custom";
			publisher.deliver(event);

			verify(handler, timeout(1000)).notifyUntyped(eq(customTopic),
					any());

			publisher.close();
		}
	}

	@DisplayName("157.3.3 Publisher Lifecycle")
	@Nested
	class PublisherLifecycleTest {

		@Test
		public void publisherIsOpenAfterCreation() {
			TypedEventPublisher<EventA> publisher = eventBus
					.createPublisher(EventA.class);

			assertThat(publisher.isOpen()).isTrue();

			publisher.close();
		}

		@Test
		public void publisherIsClosedAfterClose() {
			TypedEventPublisher<EventA> publisher = eventBus
					.createPublisher(EventA.class);

			publisher.close();

			assertThat(publisher.isOpen()).isFalse();
		}

		@Test
		public void closeIsIdempotent() {
			TypedEventPublisher<EventA> publisher = eventBus
					.createPublisher(EventA.class);

			publisher.close();
			publisher.close();
			publisher.close();

			assertThat(publisher.isOpen()).isFalse();
		}

		@Test
		public void deliverAfterCloseThrowsIllegalStateException() {
			TypedEventPublisher<EventA> publisher = eventBus
					.createPublisher(EventA.class);

			publisher.close();

			EventA event = new EventA();
			event.a = "test";

			assertThatThrownBy(() -> publisher.deliver(event))
					.isInstanceOf(IllegalStateException.class);
		}

		@Test
		public void deliverUntypedAfterCloseThrowsIllegalStateException() {
			TypedEventPublisher<EventA> publisher = eventBus
					.createPublisher(EventA.class);

			publisher.close();

			Map<String, Object> event = new HashMap<>();
			event.put("a", "test");

			assertThatThrownBy(() -> publisher.deliverUntyped(event))
					.isInstanceOf(IllegalStateException.class);
		}

		@Test
		public void getTopicWorksAfterClose() {
			TypedEventPublisher<EventA> publisher = eventBus
					.createPublisher(EventA.class);

			publisher.close();

			assertThat(publisher.getTopic()).isEqualTo(TOPIC_A);
		}

		@SuppressWarnings("resource")
		@Test
		public void tryWithResourcesAutoClose() {
			TypedEventPublisher<EventA> publisher;

			try (TypedEventPublisher<EventA> p = eventBus
					.createPublisher(EventA.class)) {
				publisher = p;
				assertThat(p.isOpen()).isTrue();
			}

			assertThat(publisher.isOpen()).isFalse();
		}

		@Test
		public void closedPublisherDoesNotDeliverEvents() {
			TypedEventPublisher<EventA> publisher = eventBus
					.createPublisher(EventA.class);

			TypedEventHandler<EventA> handler = mock(TypedEventHandlerA.class);
			context.registerService(TypedEventHandler.class, handler,
					dictionaryOf(TypedEventConstants.TYPED_EVENT_TYPE,
							EventA.class.getName()));

			publisher.close();

			EventA event = new EventA();
			event.a = "test";

			try {
				publisher.deliver(event);
			} catch (IllegalStateException e) {
				// Expected
			}

			verify(handler, after(500).never()).notify(any(), any());
		}
	}

	@DisplayName("157.3.4 Publisher Error Handling")
	@Nested
	class PublisherErrorHandlingTest {

		@Test
		public void deliverNullEventThrowsNullPointerException() {
			TypedEventPublisher<EventA> publisher = eventBus
					.createPublisher(EventA.class);

			assertThatThrownBy(() -> publisher.deliver(null))
					.isInstanceOf(NullPointerException.class);

			publisher.close();
		}

		@Test
		public void deliverUntypedNullMapThrowsNullPointerException() {
			TypedEventPublisher<EventA> publisher = eventBus
					.createPublisher(EventA.class);

			assertThatThrownBy(() -> publisher.deliverUntyped(null))
					.isInstanceOf(NullPointerException.class);

			publisher.close();
		}
	}
}
