#!/bin/bash

CURRENT_TIME=`date +"%F %T"`
date -s "2000-01-01 00:00:00"

keytool -genkey -alias test_expired -keyalg RSA -keysize 1024 -sigalg MD5WithRSA -validity 1 -keystore ../keystore -keypass testtest -storepass testtest -dname "CN=John Smith,O=ACME Inc,OU=ACME Cert Authority,L=Austin,ST=Texas,C=US"

date -s "$CURRENT_TIME"
