/*
 * Copyright (c) OSGi Alliance (2011). All Rights Reserved.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.osgi.service.subsystem;

import java.io.InputStream;
import java.util.Collection;
import java.util.Locale;
import java.util.Map;

import org.osgi.framework.BundleContext;
import org.osgi.framework.Version;
import org.osgi.framework.hooks.resolver.ResolverHook;
import org.osgi.framework.resource.Resource;
import org.osgi.service.repository.Repository;
import org.osgi.service.resolver.Resolver;

/**
 * A subsystem is a collection of resources constituting a logical, possibly
 * isolated, unit of functionality. There are three types of standard resources.
 * <ul>
 * 		<li>Bundle - A bundle that is not a fragment.
 * 		</li>
 * 		<li>Fragment - A fragment bundle.
 * 		</li>
 * 		<li>Subsystem - A subsystem defined by this specification.
 * 		</li>
 * </ul>
 * A scoped subsystem is isolated according to its share policy, which may be
 * implicit or explicit. An unscoped subsystem is not isolated and, therefore,
 * has no share policy. There are three standard types of subsystems.
 * <ul>
 * 		<li>Application - An implicitly scoped subsystem. Nothing is exported.
 *          Imports are computed based on any requirements not satisfied by the
 *          constituents.
 *     </li>
 * 		<li>Composite - An explicitly scoped subsystem. The share policy is
 *          defined by metadata within the subsystem archive.
 *     </li>
 * 		<li>Feature - An unscoped subsystem.
 *     </li>
 * </ul>
 * A subsystem may have children and, unless it's the root, must have at least
 * one parent. A subsystem becomes a child of the installing subsystem. An
 * unscoped subsystem may have more than one parent if, for example, it is a
 * constituent of more than one subsystem within the same region. A scoped
 * subsystem always has only one parent. 
 * <p/>
 * A subsystem has several unique identifiers that may or may not equate to the
 * same instance.
 * <ul>
 * 		<li>Location - An identifier specified by the client as part of
 *          installation. It is guaranteed to be unique within the same
 *          framework. Subsystems with the same location are the same instance.
 *     </li>
 * 		<li>ID - An identifier generated by the implementation as part of
 *          installation. It is guaranteed to be unique within the same
 *          framework. Subsystems with the same ID are the same instance.
 *     </li>
 * 		<li>Symbolic Name/Version - The combination of symbolic name and version
 *          uniquely identifies a subsystem but not necessarily the same
 *          instance.
 *     </li>
 * </ul>
 * The resolution of a subsystem may be mandatory or optional for a given
 * resource. Optional resources do not prevent the subsystem from installing,
 * although they may prevent it from resolving.
 * <p/>
 * A subsystem may either accept or reject transitive resources as part of its
 * provision policy. A transitive resource provides a capability (called a
 * transitive dependency) for a content resource's requirement that was not
 * satisfied by any content resource in the subsystem. A transitive resource
 * becomes a constituent of the subsystem with a provision policy of accept
 * transitive and that lies on the longest path between the subsystem and the
 * root subsystem, inclusively.
 * <p/>
 * Conceptually, a subsystem may be thought of as existing in a region isolated
 * by a share policy. Each region has one and only one scoped subsystem, which
 * dictates the sharing policy. The region may, however, have many unscoped
 * subsystems. It is therefore possible to have shared constituents across
 * multiple subsystems within a region.
 * <p/>
 * The subsystem graph may be though of as is an acyclic digraph with the root 
 * subsystem as the sole source vertex. The edges have the child as the head and
 * parent as the tail.
 * <p/>
 * A subsystem archive is a ZIP file having an SSA extension and containing
 * metadata describing the subsystem. The form of the metadata may be a
 * subsystem or deployment manifest, as well as any resource files constituting
 * the subsystem. The manifests are optional and will be computed if not
 * present. The subsystem manifest headers may be retrieved using the default or
 * a specified locale.
 * <p/>
 * A subsystem is installed using one of the two install methods. Because a
 * subsystem must be used to install other subsystems, a root subsystem is
 * provided as a starting point. A subsystem may be obtained by invoking one of
 * the install methods or through the service registry. Every installed
 * subsystem has a corresponding service registration. A bundle requesting a
 * subsystem service will receive the subsystem of which it is a constituent.
 * <p/>
 * The root subsystem has the following characteristics.
 * <ul>
 * <li>An ID of 0.</li>
 * <li>A symbolic name of org.osgi.service.subsystem.root.</li>
 * <li>A version that matches this specification's version.</li>
 * <li>Has no parent.</li>
 * <li>All existing bundles, including the system and subsystems implementation
 *     bundles, are constituents.</li>
 * <li>A scoped subsystem with a provision policy of accept transitive.</li>
 * </ul>
 * A subsystem service has the following properties.
 * <ul>
 * <li>subsystem.id</li>
 * <li>subsystem.symbolic.name</li>
 * <li>subsystem.version</li>
 * <li>subsystem.type</li>
 * <li>subsystem.state</li>
 * </ul>
 * <p/>
 * Each subsystem has an associated bundle providing the region context within 
 * which its constituents operate. All subsystems within the same region have
 * the same context. This context may be used, for example, to monitor framework
 * and service events affecting the constituents of subsystems within the
 * region. A region context bundle has the following characteristics.
 * <ul>
 * 		<li>A symbolic name of 
 *          org.osgi.service.subsystem.region.context.&lt;subsystem id&gt;.
 * 		</li>
 * 		<li>A version that matches this specification's version.
 * 		</li>
 * 		<li>A location string of &lt;subsystem bundle location&gt;/&lt;subsystem
 *          bundle id&gt;
 *      </li>
 * </ul>
 * 
 * @ThreadSafe
 * @noimplement
 */
public interface Subsystem {
	/**
	 * Identifies the category a resource falls under for the purpose of
	 * filtering the results when {@link Subsystem#getResources(
	 * ResourceCategory...) retrieving} resources associated with this
	 * subsystem.
	 * <p/>
	 * Resource categories may be compatible or incompatible. A resource may
	 * be in more than one compatible category but never in more than one
	 * incompatible category. Incompatible categories are listed in the
	 * following table.
	 * <p/>
	 * <table border="1">
	 * 		<tr align="center">
	 * 			<th>Category</th>
	 * 			<th>Incompatible With</th>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>CONTENT</td>
	 * 			<td>TRANSITIVE_DEPENDENCY, TRANSITIVE_ACCEPTED</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>TRANSITIVE_DEPENDENCY</td>
	 * 			<td>CONTENT</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>TRANSITIVE_ACCEPTED</td>
	 * 			<td>CONTENT</td>
	 * 		</tr>
	 * </table>
	 */
	public static enum ResourceCategory {
		/**
		 * A resource contained by this subsystem.
		 */
		CONSTITUENT,
		/**
		 * A constituent resource specified as part of this subsystem's
		 * {@link SubsystemConstants#SUBSYSTEM_CONTENT content} manifest header.
		 */
		CONTENT,
		/**
		 * A resource providing a capability that satisfies a transitive
		 * dependency of this subsystem.
		 */
		TRANSITIVE_DEPENDENCY,
		/**
		 * A constituent resource placed here due to this subsystem's {@link
		 * SubsystemConstants#PROVISION_POLICY_DIRECTIVE provision policy} of
		 * {@link SubsystemConstants#PROVISION_POLICY_ACCEPT_TRANSITIVE accept
		 * transitive}.
		 */
		TRANSITIVE_ACCEPTED,
		/**
		 * A constituent resource that is also a constituent of at least one
		 * other subsystem. Equivalently, a constituent resource whose reference
		 * count is greater than one.
		 */
		SHARED
	}
	
	/**
	 * The states of a subsystem in the framework. These states match those of 
	 * a Bundle and are derived using the same rules as CompositeBundles. As 
	 * such, they are more a reflection of what content bundles are permitted 
	 * to do rather than an aggregation of the content bundle states. 
	 */
	public static enum State {
		/**
		 * A subsystem is in the INSTALLING state when it is initially created.
		 */
		INSTALLING,
		/**
		 * A subsystem is in the INSTALLED state when all resources are
		 * successfully installed.
		 */
		INSTALLED,
		/**
		 * A subsystem is in the INSTALL_FAILED state when an unrecoverable
		 * error occurred during installation.
		 */
		INSTALL_FAILED,
		/**
		 *  A subsystem in the RESOLVING is allowed to have its content bundles 
		 * resolved.
		 */
		RESOLVING,
		/**
		 *  A subsystem is in the RESOLVED state when all resources are 
		 * resolved.
		 */
		RESOLVED,
		/**
		 * A subsystem is in the STARTING state when all its content bundles 
		 * are enabled for activation.
		 */
		STARTING,
		/**
		 * A subsystem is in the ACTIVE state when it has reached the beginning 
		 * start-level (for starting it's contents), and all its persistently 
		 * started content bundles that are resolved and have had their 
		 * start-levels met have completed, or failed, their activator start 
		 * method.
		 */
		ACTIVE,
		/**
		 *  A subsystem in the STOPPING state is in the process of taking its 
		 * its active start level to zero, stopping all the content bundles.
		 */
		STOPPING,
		/**
		 * A subsystem in the UNINSTALLING state is in the process of
		 * uninstalling its constituent resources.
		 */
		UNINSTALLING,
		/**
		 * A subsystem is in the UNINSTALLED state when all its content bundles 
		 * and uninstalled and its system bundle context is invalidated.
		 */
		UNINSTALLED
	}
	
	/**
	 * Returns the bundle context of the region within which this subsystem
	 * resides.
	 * <p/>
	 * The bundle context offers the same perspective of any resource contained
	 * by a subsystem within the region. It may be used, for example, to monitor
	 * events internal to the region as well as external events visible to the
	 * region. All subsystems within the same region have the same bundle
	 * context. If this subsystem is in a state where the bundle context would
	 * be invalid, null is returned.
	 * 
	 * @return The bundle context of the region within which this subsystem
	 *         resides or null if this subsystem's state is in {INSTALL_FAILED,
	 *         UNINSTALLED}.
	 * @throws SecurityException If the caller does not have the appropriate 
	 *         SubsystemPermission[this,CONTEXT], and the runtime supports 
	 *         permissions.
	 */
	public BundleContext getBundleContext();
	
	/**
	 * Returns the child subsystems of this subsystem.
	 * <p/>
	 * The returned collection is an immutable snapshot of all subsystems that
	 * are installed in this subsystem. The collection will be empty if no
	 * subsystems are installed in this subsystem.
	 * 
	 * @return The child subsystems of this subsystem.
	 * @throws IllegalStateException If this subsystem's state is in
	 *         {INSTALL_FAILED, UNINSTALLED}.
	 */
	public Collection<Subsystem> getChildren();
	
	/**
	 * Returns this subsystem's manifest headers.
	 * <p/>
	 * The returned map is unmodifiable and may be empty if this subsystem has
	 * no headers. Each map key is a header name, and each map value is the
	 * corresponding header value. Because header names are case-insensitive,
	 * the methods of the map must treat them in a case-insensitive manner. If
	 * the header name is not found, null is returned. All headers listed in the
	 * main section of the provided subsystem manifest, if any, will be
	 * included.
	 * <p/>
	 * The header values are translated according to the specified locale. If
	 * the specified locale is null or not supported, the raw values are
	 * returned. If the translation for a particular header is not found, the
	 * raw value is returned.
	 * <p/>
	 * This method must continue to return this subsystem's headers while this
	 * subsystem is in the {@link State#UNINSTALLED UNINSTALLED} state.
	 * 
	 * @param locale The locale for which translations are desired.
	 * @return The manifest headers for this subsystem.
	 * @throws SecurityException If the caller does not have the appropriate 
	 *         SubsystemPermission[this,METADATA], and the runtime supports 
	 *         permissions.
	 */
	public Map<String, String> getHeaders(Locale locale);
	
	/**
	 * Returns the location identifier of this subsystem.
	 * <p/>
	 * The location identifier is the {@code location} that was passed to the
	 * {@link #install(String, InputStream) install} method of the {@link
	 * #getParents() parent} subsystem. It is unique within the framework.
	 * <p/>
	 * This method must continue to return this subsystem's location while this
	 * subsystem is in the {@link State#UNINSTALLED UNINSTALLED} state.
	 * 
	 * @return The location identifier of this subsystem.
	 * @throws SecurityException If the caller does not have the appropriate 
	 *         SubsystemPermission[this,METADATA], and the runtime supports 
	 *         permissions.
	 */
	public String getLocation();
	
	/**
	 * Returns the parent subsystems of this subsystem.
	 * <p/>
	 * The returned collection is an immutable snapshot of all subsystems in
	 * which this subsystem is installed. The collection will be empty for the
	 * root subsystem; otherwise, it will contain at least one parent. Scoped
	 * subsystems always have only one parent. Unscoped subsystems may have
	 * multiple parents.
	 * 
	 * @return The parent subsystems of this subsystem.
	 * @throws IllegalStateException If this subsystem's state is in
	 *         {INSTALL_FAILED, UNINSTALLED}.
	 */
	public Collection<Subsystem> getParents();
	
	/**
	 * Returns the {@link ResourceCategory categorized} resources associated
	 * with this subsystem.
	 * <p/>
	 * The returned collection is an immutable snapshot of resources associated
	 * with this subsystem filtered by the specified categories. Resources that
	 * fall under more than one category will not appear more than once. If the
	 * specified categories are null or an empty array, all resources are
	 * returned. If no resources fall under any category, the collection will be
	 * empty.
	 * 
	 * @param categories The categories for which resources are desired.
	 * @return The {@link ResourceCategory categorized} resources associated
	 *         with this subsystem.
	 * @throws IllegalStateException If this subsystem's state is in
	 *         {INSTALL_FAILED, UNINSTALLED}.
	 */
	public Collection<Resource> getResources(ResourceCategory...categories);
	
	/**
	 * Returns the current state of this subsystem.
	 * <p/>
	 * This method must continue to return this subsystem's state while this
	 * subsystem is in the {@link State#UNINSTALLED UNINSTALLED} state.
	 * 
	 * @return The current state of this subsystem.
	 */
	public State getState();
	
	/**
	 * Returns the identifier of this subsystem.
	 * <p/>
	 * The identifier is a monotonically increasing, non-negative integer
	 * automatically generated at installation time and guaranteed to be unique
	 * within the framework. The identifier of the root subsystem is zero.
	 * <p/>
	 * This method must continue to return this subsystem's ID while this
	 * subsystem is in the {@link State#UNINSTALLED UNINSTALLED} state.
	 * 
	 * @return The identifier of this subsystem.
	 */
	public long getSubsystemId();
	
	/**
	 * Returns the symbolic name of this subsystem.
	 * <p/>
	 * The subsystem symbolic name conforms to the same grammar rules as the
	 * bundle symbolic name and is derived from one of the following, in order.
	 * <ul>
	 * 		<li>The value of the Subsystem-Content header, if specified.
	 * 		</li>
	 * 		<li>The subsystem URI if passed as the location along with the
	 *          content to the install method.
	 *      </li>
	 * 		<li>Optionally generated in an implementation specific way.
	 * 		</li>
	 * </ul>
	 * The combination of symbolic name and version is unique within a region.
	 * The symbolic name of the root subsystem is {@code
	 * org.osgi.service.subsystem.root}.
	 * <p/>
	 * This method must continue to return this subsystem's symbolic name while
	 * this subsystem is in the {@link State#UNINSTALLED UNINSTALLED} state.
	 * 
	 * @return The symbolic name of this subsystem.
	 */
	public String getSymbolicName();
	
	/**
	 * Returns the {@link SubsystemConstants#SUBSYSTEM_TYPE type} of this
	 * subsystem.
	 * <p/>
	 * The type of the root subsystem is {@link SubsystemConstants#
	 * SUBSYSTEM_TYPE_COMPOSITE composite}. This method must continue to return
	 * this subsystem's type while this subsystem is in the {@link State#
	 * UNINSTALLED UNINSTALLED} state.
	 * 
	 * @return The {@link SubsystemConstants#SUBSYSTEM_TYPE type} of this
	 *         subsystem.
	 */
	public String getType();
	
	/**
	 * Returns the version of this subsystem.
	 * <p/>
	 * The subsystem version conforms to the same grammar rules as the bundle
	 * version and is derived from one of the following, in order.
	 * <ul>
	 * 		<li>The value of the Subsystem-Version header, if specified.
	 * 		</li>
	 * 		<li>The subsystem URI if passed as the location along with the
	 *          content to the install method.
	 *      </li>
	 * 		<li>Defaults to {@code 0.0.0}.
	 * 		</li>
	 * </ul>
	 * The combination of symbolic name and version is unique within a region.
	 * The version of the root subsystem matches this specification's version.
	 * <p/>
	 * This method must continue to return this subsystem's version while this
	 * subsystem is in the {@link State#UNINSTALLED UNINSTALLED} state.
	 * 
	 * @return The version of this subsystem.
	 */
	public Version getVersion();
	
	/**
	 * Installs a subsystem from the specified <code>location</code> identifier.
	 * <p/>
	 * This method performs the same function as calling {@link #install(String,
	 * InputStream)} with the specified <code>location</code> identifier and a
	 * <code>null</code> InputStream.
	 * 
	 * @param location - The location identifier of the subsystem to install.
	 * @return The installed subsystem.
	 * @throws IllegalStateException If this subsystem's state is in {INSTALLING
	 *         , INSTALL_FAILED, UNINSTALLING, UNINSTALLED}.
	 * @throws SubsystemException If the installation failed.
	 * @throws SecurityException If the caller does not have the appropriate 
	 *         SubsystemPermission[installed subsystem,LIFECYCLE], and the Java 
	 *         Runtime Environment supports permissions.
	 * @see #install(String, InputStream)
	 */
	public Subsystem install(String location) throws SubsystemException;
	
	/**
	 * Installs a subsystem from the specified {@code content}.
	 * <p/>
	 * The specified {@code location} will be used as an identifier of the
	 * subsystem. Every installed subsystem is uniquely identified by its
	 * location, which is typically in the form of a URI. If the specified
	 * {@code location} conforms to the {@code subsystem-uri} grammar, the
	 * required symbolic name and optional version information will be used as
	 * default values.
	 * <p/>
	 * If the specified {@code content} is null, a new input stream must be
	 * created from which to read the subsystem by interpreting, in an
	 * implementation dependent manner, the specified {@code location}. 
	 * <p/>
	 * A subsystem installation must be persistent. That is, an installed
	 * subsystem must remain installed across Framework and VM restarts.
	 * <p/>
	 * All references to changing the state of this subsystem include both
	 * changing the state of the subsystem object as well as the state property
	 * of the subsystem service registration. 
	 * <p/>
	 * Implementations should be sensitive to the potential for long running
	 * operations and periodically check the current thread for interruption. An
	 * interrupted thread should result in a SubsystemException with an
	 * InterruptedException as the cause and be treated as an installation
	 * failure.
	 * <p/>
	 * All installation failure flows include the following, in order.
	 * <ol>
	 * 		<li>Uninstall all resources installed as part of this operation.
	 *      </li>
	 * 		<li>Change the state to INSTALL_FAILED.
	 * 		</li>
	 *      <li>Unregister the subsystem service.
	 *      </li>
	 *      <li>Uninstall the region context bundle.
	 *      </li>
	 *      <li>Throw a SubsystemException with the specified cause.
	 *      </li>
	 * </ol>
	 * The following steps are required to install a subsystem. 
	 * <ol>
	 * <li>If an installed subsystem with the specified {@code location}
	 *     identifier already exists, return the installed subsystem.
	 * </li>
	 * <li>Read the specified {@code content} in order to determine the symbolic
	 *     name, version, and type of the installing subsystem. If an error
	 *     occurs while reading the content, an installation failure results.
	 * </li>
	 * <li>If an installed subsystem with the same symbolic name and version
	 *     already exists within this subsystem's region, complete the
	 *     installation with one of the following.
	 *     <ul>
	 *     <li>If the installing and installed subsystems' types are not equal,
	 *         an installation failure results.
	 *     </li>
	 *     <li>If the installing and installed subsystems' types are equal, and
	 *         the installed subsystem is already a child of this subsystem,
	 *         return the installed subsystem.
	 *     </li>
	 *     <li>If the installing and installed subsystems' types are equal, and
	 *         the installed subsystem is not already a child of this subsystem,
	 *         add the installed subsystem as a child of this subsystem,
	 *         increment the installed subsystem's reference count by one, and
	 *         return the installed subsystem.
	 *     </li>
	 *     </ul>
	 * </li>
	 * <li>Create a new subsystem based on the specified {@code location} and
	 *     {@code content}.
	 * </li>
	 * <li>If the subsystem is scoped, install and activate a new region context
	 *     bundle.
	 * </li>
	 * <li>Change the state to INSTALLING and register a new subsystem service.
	 * </li>
	 * <li>{@link Repository Discover} the subsystem's content resources. If any
	 *     mandatory resource is missing, an installation failure results.
	 * </li>
	 * <li>{@link Resolver Discover} the transitive resources required by the
	 *     content resources. If any transitive resource is missing, an
	 *     installation failure results.
	 * </li>
	 * <li>{@link ResolverHook Disable} runtime resolution for the resources.
	 * </li>
	 * <li>Install the transitive resources. If any transitive resource fails
	 *     to install, an installation failure results.
	 * </li>
	 * <li>Install the content resources. If any content resource fails to
	 *     install, an installation failure results.
	 * </li>
	 * <li>If the subsystem is scoped, enable the import sharing policy.
	 * </li>
	 * <li>Enable runtime resolution for the resources.
	 * </li>
	 * <li>Change the state of the subsystem to INSTALLED.
	 * </li>
	 * <li>Return the new subsystem.
	 * </li>
	 * </ol>
	 * 
	 * @param location - The location identifier of the subsystem to be
	 *        installed.
	 * @param content - The input stream from which this subsystem will be read
	 *        or null to indicate the input stream must be created from the
	 *        specified location identifier. The input stream will always be
	 *        closed when this method completes, even if an exception is thrown.
	 * @return The installed subsystem.
	 * @throws IllegalStateException If this subsystem's state is in {INSTALLING
	 *         , INSTALL_FAILED, UNINSTALLING, UNINSTALLED}.
	 * @throws SubsystemException If the installation failed.
	 * @throws SecurityException If the caller does not have the appropriate 
	 *         SubsystemPermission[installed subsystem,LIFECYCLE], and the runtime
	 *         supports permissions.
	 */
	public Subsystem install(String location, InputStream content) throws SubsystemException;
	
	/**
	 * Starts this subsystem.
	 * <p/>
	 * The following table shows which actions are associated with each state.
	 * An action of Wait means this method will block until a state transition
	 * occurs, upon which the new state will be evaluated in order to
	 * determine how to proceed. An action of Return means this method returns
	 * immediately without taking any other action.
	 * <p/>
	 * <table border="1">
	 * 		<tr>
	 * 			<th>State</td>
	 * 			<th>Action</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>INSTALLING</td>
	 * 			<td>Wait</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>INSTALLED</td>
	 * 			<td>Resolve, Start</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>INSTALL_FAILED</td>
	 * 			<td>IllegalStateException</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>RESOLVING</td>
	 * 			<td>Wait</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>RESOLVED</td>
	 * 			<td>If this subsystem is in the process of being<br/>
	 *              started, Wait. Otherwise, Uninstall.</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>STARTING</td>
	 * 			<td>Wait</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>ACTIVE</td>
	 * 			<td>Return</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>STOPPING</td>
	 * 			<td>Wait</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>UNINSTALLING</td>
	 * 			<td>IllegalStateException</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>UNINSTALLED</td>
	 * 			<td>IllegalStateException</td>
	 * 		</tr>
	 * </table>
	 * <p/>
	 * All references to changing the state of this subsystem include both
	 * changing the state of the subsystem object as well as the state property
	 * of the subsystem service registration.
	 * <p/>
	 * Implementations should be sensitive to the potential for long running
	 * operations and periodically check the current thread for interruption. An
	 * interrupted thread should be treated as a start failure with an
	 * InterruptedException as the cause.
	 * <p/>
	 * All start failure flows include the following, in order.
	 * <ol>
	 * 		<li>Stop all resources that were started as part of this operation.
	 *      </li>
	 *      <li>Disable the export sharing policy.
	 *      </li>
	 *      <li>Change the state to either INSTALLED or RESOLVED.
	 * 		</li>
	 * 		<li>Throw a SubsystemException with the specified cause.
	 *      </li>
	 * </ol>
	 * <p/>
	 * A subsystem must be persistently started. That is, a started subsystem
	 * must be restarted across Framework and VM restarts, even if a start
	 * failure occurs.
	 * <p/>
	 * The following steps are required to start this subsystem.
	 * <ol>
	 * 		<li>If this subsystem is in the RESOLVED state, proceed to step 5.
	 * 		</li>
	 *      <li>Change the state to RESOLVING.
	 *      </li>
	 *      <li>Resolve the content resources. A resolution failure results in
	 *          a start failure with a state of INSTALLED.
	 *      </li>
	 *      <li>Change the state to RESOLVED.
	 *      </li>
	 *      <li>If this subsystem is scoped, enable the export sharing policy.
	 * 		</li>
	 * 		<li>Change the state to STARTING.
	 *      </li>
	 *      <li>For each eligible resource, increment the activation count by
	 *          one. If the activation count is one, start the resource. All
	 *          transitive resources must be started before any content
	 *          resource, and content resources must be started according to the
	 *          specified {@link SubsystemConstants#START_LEVEL_DIRECTIVE start
	 *          order}. If an error occurs while starting a resource, a start
	 *          failure results with that error as the cause.
	 *      </li>
	 *      <li>Change the state to ACTIVE.
	 * 		</li>
	 * </ol>
	 * <p/> 
	 * @throws SubsystemException If this subsystem fails to start. 
	 * @throws IllegalStateException If this subsystem's state is in
	 *         {INSTALL_FAILED, UNINSTALLING, or UNINSTALLED}, or if the state
	 *         of at least one of this subsystem's parents is not in {STARTING,
	 *         ACTIVE}.
	 * @throws SecurityException If the caller does not have the appropriate 
	 *         SubsystemPermission[this,EXECUTE], and the runtime supports 
	 *         permissions.
	 */
	public void start() throws SubsystemException;
	
	/**
	 * Stops this subsystem.
	 * <p/>
	 * The following table shows which actions are associated with each state.
	 * An action of Wait means this method will block until a state transition
	 * occurs, upon which the new state will be evaluated in order to
	 * determine how to proceed. An action of Return means this method returns
	 * immediately without taking any other action.
	 * <p/>
	 * <table border="1"">
	 * 		<tr>
	 * 			<th>State</td>
	 * 			<th>Action</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>INSTALLING</td>
	 * 			<td>Wait</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>INSTALLED</td>
	 * 			<td>Return</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>INSTALL_FAILED</td>
	 * 			<td>IllegalStateException</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>RESOLVING</td>
	 * 			<td>Wait</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>RESOLVED</td>
	 * 			<td>If this subsystem is in the process of being<br/>
	 *              started, Wait. Otherwise, Return.</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>STARTING</td>
	 * 			<td>Wait</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>ACTIVE</td>
	 * 			<td>Stop</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>STOPPING</td>
	 * 			<td>Wait</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>UNINSTALLING</td>
	 * 			<td>IllegalStateException</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>UNINSTALLED</td>
	 * 			<td>IllegalStateException</td>
	 * 		</tr>
	 * </table>
	 * <p/>
	 * Implementations should be sensitive to the potential for long running
	 * operations and periodically check the current thread for interruption, in
	 * which case a SubsystemException with an InterruptedException as the cause
	 * should be thrown. If an interruption occurs while waiting, this method
	 * should terminate immediately. Once the transition to the STOPPING
	 * state has occurred, however, this method must not terminate due to an
	 * interruption until the stop process has completed.
	 * <p/>
	 * A subsystem must be persistently stopped. That is, a stopped subsystem
	 * must remain stopped across Framework and VM restarts.
	 * <p/>
	 * All references to changing the state of this subsystem include both
	 * changing the state of the subsystem object as well as the state property
	 * of the subsystem service registration.
	 * <p/>
	 * The following steps are required to stop this subsystem.
	 * <ol>
	 * 		<li>Change the state to STOPPING.
	 * 		</li>
	 * 		<li>For each eligible resource, decrement the activation count by
	 *          one. If the activation count is zero, stop the resource. All
	 *          content resources must be stopped before any transitive
	 *          resource, and content resources must be stopped in reverse
	 *          {@link SubsystemConstants#START_LEVEL_DIRECTIVE start order}. If
	 *          an error occurs while stopping a resource, a stop failure
	 *          results with that error as the cause.
	 *      </li>
	 *      <li>Change the state to RESOLVED.
	 *      </li>
	 * </ol>
	 * With regard to error handling, once this subsystem has transitioned to
	 * the STOPPING state, every part of each step above must be attempted.
	 * Errors subsequent to the first should be logged. Once the stop process
	 * has completed, a SubsystemException must be thrown with the initial error
	 * as the specified cause.
	 * <p/>
	 * @throws SubsystemException If this subsystem fails to stop cleanly.
	 * @throws IllegalStateException If this subsystem's state is in
	 *         {INSTALL_FAILED, UNINSTALLING, or UNINSTALLED}.
	 * @throws SecurityException If the caller does not have the appropriate 
	 *         SubsystemPermission[this,EXECUTE], and the runtime supports 
	 *         permissions.
	 */
	public void stop() throws SubsystemException;
	
	/**
	 * Uninstalls this subsystem.
	 * <p/>
	 * The following table shows which actions are associated with each state.
	 * An action of Wait means this method will block until a state transition
	 * occurs, upon which the new state will be evaluated in order to
	 * determine how to proceed. An action of Return means this method returns
	 * immediately without taking any other action.
	 * <p/>
	 * <table border="1">
	 * 		<tr>
	 * 			<th>State</td>
	 * 			<th>Action</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>INSTALLING</td>
	 * 			<td>Wait</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>INSTALLED</td>
	 * 			<td>Uninstall</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>INSTALL_FAILED</td>
	 * 			<td>IllegalStateException</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>RESOLVING</td>
	 * 			<td>Wait</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>RESOLVED</td>
	 * 			<td>If this subsystem is in the process of being<br/>
	 *              started, Wait. Otherwise, Uninstall.</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>STARTING</td>
	 * 			<td>Wait</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>ACTIVE</td>
	 * 			<td>Stop, Uninstall</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>STOPPING</td>
	 * 			<td>Wait</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>UNINSTALLING</td>
	 * 			<td>Wait</td>
	 * 		</tr>
	 * 		<tr align="center">
	 * 			<td>UNINSTALLED</td>
	 * 			<td>Return</td>
	 * 		</tr>
	 * </table>
	 * <p/>
	 * Implementations should be sensitive to the potential for long running
	 * operations and periodically check the current thread for interruption, in
	 * which case a SubsystemException with an InterruptedException as the cause
	 * should be thrown. If an interruption occurs while waiting, this method
	 * should terminate immediately. Once the transition to the UNINSTALLING
	 * state has occurred, however, this method must not terminate due to an
	 * interruption until the uninstall process has completed.
	 * <p/>
	 * All references to changing the state of this subsystem include both
	 * changing the state of the subsystem object as well as the state property
	 * of the subsystem service registration.
	 * <p/>
	 * The following steps are required to uninstall this subsystem.
	 * <ol>
	 * 		<li>Change the state to UNINSTALLING.
	 * 		</li>
	 * 		<li>Uninstall each content resource.
	 *      </li>
	 *      <li>Uninstall each transitive resource.
	 *      </li>
	 *      <li>Change the state to UNINSTALLED.
	 *      </li>
	 *      <li>Unregister the subsystem service.
	 *      </li>
	 *      <li>Uninstall the region context bundle.
	 *      </li>
	 * </ol>
	 * With regard to error handling, once this subsystem has transitioned to
	 * the UNINSTALLING state, every part of each step above must be attempted.
	 * Errors subsequent to the first should be logged. Once the uninstall
	 * process has completed, a SubsystemException must be thrown with the
	 * specified cause.
	 * <p/>
	 * @throws SubsystemException If this subsystem fails to uninstall, or the
	 *         current thread is interrupted.
	 * @throws IllegalStateException If this subsystem's state is in
	 *         {INSTALL_FAILED}. 
	 * @throws SecurityException If the caller does not have the appropriate 
	 *         SubsystemPermission[this,LIFECYCLE], and the runtime supports
	 *         permissions.
	 */
	public void uninstall() throws SubsystemException;
}
