ROOT = ../../../../../..

NAME = StartLevelControl
PACKAGE = org.osgi.test.cases.startlevel.tbc
VERSION = 1.0
DESC = "Tests the start level service"
ON_TARGET	= true

SOURCES = \
	StartLevelControl.java

include $(ROOT)/cnf/testbundle.mk

