ROOT   = ../../../../..

NAME		= HttpTestCase
PACKAGE 	= org.osgi.test.cases.http
VERSION     = 3.0
DESC        = "Tests the Http Service"
IMPORTS		= $(ROOT)/jar/servlet.jar

BEFORE 		= tbc 

SOURCES = \
	HttpTestCase.java

BTOOLPARAMS = \
	$(IMPORTTBC) \
	$(IMPORTLOG)


include $(ROOT)/cnf/testcase.mk

